# Generated by Django 5.2.7 on 2025-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
