# Generated by Django 5.2.7 on 2025-12-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userencryptionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='key_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userencryptionkey',
            name='encrypted_private_key_backup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userencryptionkey',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RoomKeyForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_room_key', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_keys', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_keys', to='chat.userprofile')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'unique_together': {('room', 'user', 'version')},
            },
        ),
    ]
