"""
Django settings for chat_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / ".env") 

# CHAT_ENCRYPTION_KEY = os.getenv("CHAT_ENCRYPTION_KEY")

# if not CHAT_ENCRYPTION_KEY:
#     raise ValueError("CHAT_ENCRYPTION_KEY env var is not set")

# from cryptography.fernet import Fernet

# Create Fernet instance (expects bytes)
# FERNET = Fernet(CHAT_ENCRYPTION_KEY.encode())

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-zk!6!#ctc3a#)i(i9b527fw$nm$jpplalbfcnzr1a18$)65*qu'

DEBUG = True

# Allow localhost during development and any ngrok subdomain
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.app",
    "glaucous-trina-frivolously.ngrok-free.dev",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chat",
    "channels",
    "rest_framework",
    "corsheaders",
]

# Middleware order: Security -> WhiteNoise -> CORS -> Session -> Common -> CSRF -> Auth -> Messages -> Clickjacking
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chat_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Make sure Django can find the built frontend index.html in frontend_build/dist
        "DIRS": [BASE_DIR / "frontend_build" / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "chat_backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files / frontend build integration
# Serve frontend build files under /static/ so MEDIA_URL does not collide
STATIC_URL = "/static/"

# collectstatic will copy files into STATIC_ROOT
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# During development, Django will also search this folder for static files (your Vite dist)
# STATICFILES_DIRS = [
#     BASE_DIR / "frontend_build" / "dist",  # should contain index.html, assets/, vite.svg
# ]

# Templates should include the dist folder so TemplateView can find index.html
# TEMPLATES[0]["DIRS"] = [BASE_DIR / "frontend_build" / "dist"]

# Media (uploads) — must be different from STATIC_URL
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Optional: WhiteNoise storage (comment out during debugging if manifest errors)
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

# CORS and CSRF settings
CORS_ALLOWED_ORIGINS = [
    "*"
]
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]

# CSRF trusted origins for ngrok (and any frontend you expose)
CSRF_TRUSTED_ORIGINS = [
    "*"
]
